import type { Metadata } from 'next'
import { Inter, Playfair_Display } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { PostHogAuthBridge } from '@/components/posthog-auth-bridge'
import './globals.css'

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter'
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: '--font-playfair'
});

export const metadata: Metadata = {
  metadataBase: new URL('https://living-art-screensaver.com'),
  // Per-page titles compose as "<Page> — Living Art Screensaver"; pages that
  // set no title fall back to `default` (used as-is, untemplated) — e.g. the
  // homepage, which carries the full "…for Mac" keyword phrase for SERPs.
  title: {
    default: 'Living Art Screensaver — AI-Animated Art Screensaver for Mac',
    template: '%s — Living Art Screensaver',
  },
  description: 'A Mac screensaver that turns your idle display into a living art gallery, showcasing AI-animated artworks across every style, with new pieces added regularly. Free Download.',
  icons: {
    icon: { url: '/icon.svg', type: 'image/svg+xml' },
    apple: '/apple-icon.png',
  },
  // Rich link previews when the site (or a shared clip) is posted to social —
  // the core of the organic-growth plan. The og:image itself is generated by
  // `app/opengraph-image.tsx` and auto-attached by Next to both og + twitter.
  openGraph: {
    type: 'website',
    siteName: 'Living Art Screensaver',
    url: 'https://living-art-screensaver.com',
    title: 'Turn your Mac into a living gallery',
    description:
      'Centuries of art, animated by AI and hung on your idle Mac — with a new piece every night. Free to download.',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Turn your Mac into a living gallery',
    description:
      'Centuries of art, animated by AI and hung on your idle Mac — with a new piece every night. Free to download.',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} ${playfair.variable} font-sans antialiased`}>
        <PostHogAuthBridge />
        {children}
        <Analytics />
      </body>
    </html>
  )
}
