import { logoSwirlPath } from "@/lib/logo-path"

/**
 * The Living Art "living swirl" — a single tapered brushstroke winding into a
 * spiral (Starry Night's sky / Hokusai's wave, reduced to clean geometry):
 * classic art in motion. Draws in `currentColor` so it works ink-on-mint
 * (inside the primary tile) and mint-on-dark alike. Geometry is generated by
 * branding/generate-logo.mjs; see branding/README.md for the rationale.
 *
 * Inside a tile badge, set `size` to the badge's full size — the mark's
 * viewBox carries its own margin, which reproduces the app icon's
 * mark-to-tile ratio exactly.
 */
export function LogoMark({ size = 24, className }: { size?: number; className?: string }) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} className={className} aria-hidden="true">
      <path d={logoSwirlPath} fill="currentColor" />
    </svg>
  )
}
